name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: stevenwdv/setup-fasm@v1

    - name: test-fasm
      run: fasm

    - name: compile
      run: make build
